Update ASO manage script for Monitor deployment

diff --git a/asyncstageout/deploy b/asyncstageout/deploy
--- a/asyncstageout/deploy
+++ b/asyncstageout/deploy
@@ -1,65 +1,383 @@
-# vim: set ft=sh sw=2 ts=8 et :
-deploy_asyncstageout_variants="default offsite"
-deploy_asyncstageout_deps()
-{
-  deploy couchdb
-  case $variant in offsite ) ;; * ) deploy bigcouch ;; esac
+#!/bin/bash
+
+
+#
+# Global variables etc
+#
+THIS_SCRIPT=$(readlink -f $0)
+PROJ_DIR=$(dirname $(dirname $THIS_SCRIPT))
+ROOT_DIR=$(dirname $(dirname $(dirname $THIS_SCRIPT)))
+
+INSTALL_AS="$ROOT_DIR/install/asyncstageout"
+INSTALL_COUCH="$ROOT_DIR/install/couchdb"
+
+CONFIG_COUCH="$ROOT_DIR/config/couchdb"
+CONFIG_AS="$ROOT_DIR/config/asyncstageout"
+
+COUCH_INIT_DONE=0
+AS_INIT_DONE=0
+
+
+COUCH_USER=couch_db_user
+COUCH_PASS=couch_db_password
+
+COUCH_HOST=127.0.0.1
+COUCH_PORT=5984
+COUCH_HOST_NAME=`hostname`
+
+
+# Flags to show which tools have been initialised
+if [ -e $INSTALL_AS/.init ]; then AS_INIT_DONE=1; else AS_INIT_DONE=0; fi;
+if [ -e $INSTALL_COUCH/.init ]; then COUCH_INIT_DONE=1; else COUCH_INIT_DONE=0; fi;
+
+#callbacks to activate or show initialisation has been done
+activate_asyncstageout(){
+    if [ ! -d "$INSTALL_AS" ]; then
+        mkdir -p $INSTALL_AS
+        mkdir -p $INSTALL_AS/Monitor/work
+        mkdir -p $INSTALL_AS/AsyncTransfer/dropbox/inputs
+        mkdir -p $INSTALL_AS/AsyncTransfer/dropbox/outputs
+    fi
+    touch $INSTALL_AS/.using
+    cp $ROOT_DIR/apps/asyncstageout/configuration/Example.py $CONFIG_AS/config-template.py
+    cp $ROOT_DIR/apps/asyncstageout/Monitor/monitor.conf $CONFIG_AS/monitor-template.conf	
 }
 
-deploy_asyncstageout_prep()
-{
-  case $variant in offsite) opts= ;; *) opts="-s -l" ;; esac
-  mkproj $opts
+inited_asyncstageout(){
+    touch $INSTALL_AS/.init
+}
+inited_couch(){
+    touch $INSTALL_COUCH/.init
 }
 
-deploy_asyncstageout_sw()
-{
-  deploy_pkg comp cms+asyncstageout
+#
+# Passwords/Secrets handling
+#
+load_secrets_file(){
+    if [ "x$WMAGENT_SECRETS_LOCATION" == "x" ]; then
+        WMAGENT_SECRETS_LOCATION=$HOME/WMAgent.secrets;
+    fi
+    if [ ! -e $WMAGENT_SECRETS_LOCATION ]; then
+        echo "Password file: $WMAGENT_SECRETS_LOCATION does not exist"
+        echo "Either set WMAGENT_SECRETS_LOCATION to a valid file or check that $HOME/WMagent.secrets exists"
+        exit 1;
+    fi
+
+    local MATCH_COUCH_USER=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_USER | sed s/COUCH_USER=//`
+    local MATCH_COUCH_PASS=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_PASS | sed s/COUCH_PASS=//`
+    local MATCH_COUCH_HOST=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_HOST | sed s/COUCH_HOST=//`
+    local MATCH_COUCH_PORT=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_PORT | sed s/COUCH_PORT=//`
+    local MATCH_COUCH_CERT_FILE=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_CERT_FILE | sed s/COUCH_CERT_FILE=//`
+    local MATCH_COUCH_KEY_FILE=`cat $WMAGENT_SECRETS_LOCATION | grep COUCH_KEY_FILE | sed s/COUCH_KEY_FILE=//`
+    local MATCH_HOST_DN=`cat $WMAGENT_SECRETS_LOCATION     | grep HOST_DN       | sed s/HOST_DN=//`
+
+    if [ "x$MATCH_COUCH_USER" == "x" ]; then
+        COUCH_USER=asynccouch;
+    else
+        COUCH_USER=$MATCH_COUCH_USER;
+    fi
+    if [ "x$MATCH_COUCH_PASS" == "x" ]; then
+        echo "Secrets file doesnt contain COUCH_PASS";
+        exit 1
+    else
+        COUCH_PASS=$MATCH_COUCH_PASS;
+    fi
+    if [ ! "x$MATCH_COUCH_PORT" == "x" ]; then
+        COUCH_PORT=$MATCH_COUCH_PORT;
+    fi
+    if [ ! "x$MATCH_COUCH_HOST" == "x" ]; then
+        COUCH_HOST=$MATCH_COUCH_HOST;
+    fi
+    # look for couch ssl certificate if not found check X509_USER_CERT and X509_USER_PROXY
+    if [ ! "x${X509_USER_CERT:-$X509_USER_PROXY}" == "x" ]; then
+        COUCH_CERT_FILE=$MATCH_COUCH_CERT_FILE;
+    elif [ ! "x$X509_USER_CERT" == "x" ]; then
+        COUCH_CERT_FILE=${X509_USER_CERT:-$X509_USER_PROXY};
+    fi
+    # look for couch ssl key if not found check X509_USER_KEY and X509_USER_PROXY
+    if [ ! "x$MATCH_COUCH_KEY_FILE" == "x" ]; then
+        COUCH_KEY_FILE=$MATCH_COUCH_KEY_FILE;
+    elif [ ! "x${X509_USER_KEY:-$X509_USER_PROXY}" == "x" ]; then
+        COUCH_KEY_FILE=${X509_USER_KEY:-$X509_USER_PROXY};
+    fi
+    if [ ! "x$MATCH_HOST_DN" == "x" ]; then
+        HOST_DN=$MATCH_HOST_DN;
+    fi
+
 }
 
-deploy_asyncstageout_post()
-{
-  case $variant in
-    offsite )
-      mkdir -p $root/current/install/couchdb
+print_settings(){
+    echo "INSTALL_AS=               $INSTALL_AS                 "
+    echo "CONFIG_COUCH=             $CONFIG_COUCH               "
+    echo "CONFIG_AS=                $CONFIG_AS                  "
+    echo "COUCH_USER=               $COUCH_USER                 "
+    echo "COUCH_PASS=               $COUCH_PASS                 "
+    echo "COUCH_HOST=               $COUCH_HOST                 "
+    echo "COUCH_PORT=               $COUCH_PORT                 "
 
-      mkdir -p $root/current/install/asyncstageout
-      mkdir -p $root/current/config/asyncstageout
-
-      # Tell couchdb to pick up AsyncTransfer on the next restart
-      # and configure replication, compaction and backup, too
-      local couchdb_config=$root/current/config/couchdb
-      local couchdb_state=$root/state/couchdb
-
-      local couchdb_ini=$root/current/config/asyncstageout/local.ini
-      perl -p -i -e "s{deploy_project_root}{$root/current/install}g" $couchdb_ini
-      cp -f $couchdb_ini $root/current/config/couchdb
-
-      for area in stagingarea replication; do
-         rm -f $couchdb_state/$area/asyncstageout
-         touch $couchdb_state/$area/asyncstageout
-      done
-      ;;
-    default )
-      # Tell couch to push the AlertsCollector couchapp on the next restart
-      for couch in couchdb:5984 bigcouch:5985; do
-        echo "couchapp push " \
-             "$root/current/apps/asyncstageout/couchapp/UserMonitoring" \
-             "http://localhost:${couch##*:}/user_monitoring_asynctransfer" \
-             > $root/state/${couch%%:*}/stagingarea/asyncstageout
-        echo "couchapp push " \
-             "$root/current/apps/asyncstageout/couchapp/AsyncTransfer" \
-             "http://localhost:${couch##*:}/asynctransfer" \
-             >> $root/state/${couch%%:*}/stagingarea/asyncstageout
-        echo "couchapp push " \
-             "$root/current/apps/asyncstageout/couchapp/DBSPublisher" \
-             "http://localhost:${couch##*:}/asynctransfer" \
-             >> $root/state/${couch%%:*}/stagingarea/asyncstageout
-        echo "couchapp push " \
-             "$root/current/apps/asyncstageout/couchapp/monitor" \
-             "http://localhost:${couch##*:}/asynctransfer" \
-             >> $root/state/${couch%%:*}/stagingarea/asyncstageout
-      done
-      ;;
-  esac
 }
+
+#
+# Environment
+#
+
+. $ROOT_DIR/apps/pystack/etc/profile.d/init.sh
+. $ROOT_DIR/apps/couchdb/etc/profile.d/init.sh
+. $ROOT_DIR/apps/asyncstageout/etc/profile.d/init.sh
+
+
+#########################
+#  CouchDB              #
+#########################
+
+#
+# first time startup for couch: disable admin party and create user based on secrets file
+#
+init_couch_pre(){
+
+    echo "Initialising CouchDB on $COUCH_HOST:$COUCH_PORT..."
+    mkdir -p $INSTALL_COUCH/logs
+    mkdir -p $INSTALL_COUCH/database
+    perl -p -i -e "s{deploy_project_root/couchdb}{$INSTALL_COUCH}" $CONFIG_COUCH/local.ini
+    # couch ini file requires IP based hostname
+    perl -p -i -e "s{bind_address = 0.0.0.0}{bind_address = $COUCH_HOST}g" $CONFIG_COUCH/local.ini
+    perl -p -i -e "s{port = 5984}{port = $COUCH_PORT}g" $CONFIG_COUCH/local.ini
+    perl -p -i -e "s{;admin = mysecretpassword}{$COUCH_USER = $COUCH_PASS}g" $CONFIG_COUCH/local.ini
+}
+
+init_couch_post(){
+    inited_couch;
+}
+
+status_of_couch(){
+    echo "+ Couch Status:"
+    if [ ! -e $INSTALL_COUCH/logs/couchdb.pid ]; then
+        echo "++ Couch process file not found"
+        return
+    fi
+    local COUCH_PID=`cat $INSTALL_COUCH/logs/couchdb.pid`
+    kill -0 $COUCH_PID;
+    local COUCH_STATUS=$?
+    if [ $COUCH_STATUS -eq 0 ]; then
+        echo "++ Couch running with process: $COUCH_PID";
+    else
+        echo "++ Couch process not running"
+    fi
+    echo "++" `curl -s $COUCH_HOST:$COUCH_PORT`
+}
+
+#
+# Startup couch
+#
+start_couch(){
+   load_secrets_file;
+   echo "starting couch..."
+   if [ $COUCH_INIT_DONE -eq 0 ]; then
+       echo "CouchDB has not been initialised... running pre initialisation";
+       init_couch_pre;
+   fi
+   couchdb -b -a $CONFIG_COUCH/local.ini \
+           -p $INSTALL_COUCH/logs/couchdb.pid \
+           -e $INSTALL_COUCH/logs/stderr.log \
+           -o $INSTALL_COUCH/logs/stdout.log
+   if [ $COUCH_INIT_DONE -eq 0 ]; then
+       echo "CouchDB has not been initialised... running post initialisation"
+       init_couch_post;
+   fi
+
+
+}
+
+#
+# shutdown couch
+#
+stop_couch(){
+   echo "stopping couch...";
+   couchdb  -d  -p $INSTALL_COUCH/logs/couchdb.pid;
+
+}
+
+clean_couch(){
+    echo "cleaning couch installation..."
+    stop_couch
+    echo "removing files"
+    rm -f $INSTALL_COUCH/.init
+    rm -rf $INSTALL_COUCH/database/*
+
+}
+
+
+#
+# combined startup of all required services
+#
+start_services(){
+    echo "Starting Services..."
+    #start up the services required by the async
+    start_couch;
+}
+
+stop_services(){
+    #shut down all services
+    echo "Shutting down services..."
+    stop_couch;
+}
+
+init_async(){
+    load_secrets_file;
+    wmagent-mod-config --input=$CONFIG_AS/config-template.py \
+                       --output=$CONFIG_AS/config.py \
+                       --couch_url=http://$COUCH_USER:$COUCH_PASS@$COUCH_HOST_NAME:$COUCH_PORT \
+                       --working_dir=$INSTALL_AS \
+                       --host_dn=$HOST_DN \
+
+    export WMAGENT_CONFIG=$CONFIG_AS/config.py
+    export ASYNC_ROOT=$ROOT_DIR/apps/asyncstageout
+    wmagent-couchapp-init;
+    unset ASYNC_ROOT
+    unset WMAGENT_CONFIG
+
+    echo "inbox  = $ROOT_DIR/install/asyncstageout/AsyncTransfer/dropbox/outputs 
+inbox_poll_interval = 30
+workdir = $ROOT_DIR/install/asyncstageout/Monitor/work
+outbox  = $ROOT_DIR/install/asyncstageout/AsyncTransfer/dropbox/inputs
+logfile = $ROOT_DIR/install/asyncstageout/Monitor/aso-monitor.log
+service = https://fts3-pilot.cern.ch:8443/
+job_poll_interval_slow = 10    # Job-polling speed when there are very few jobs
+job_poll_interval_fast = 0.3   # Job-polling speed when there are lots of jobs
+job_parallelism        = 8     # Maximum number of jobs to poll in parallel
+per_job_poll_interval  = 7     # for each job in the queue, do not poll it more frequently than this interval
+job_timeout            = 43200 # Timeout for transfer job completion
+file_timeout           = 3600
+verbose = 1" > $CONFIG_AS/monitor.conf
+
+      echo "#unset PERL5LIB
+root=$ROOT_DIR 
+#. \$root/sw*/slc*/cms/PHEDEX-micro/*/etc/profile.d/init.sh 
+#. \$root/sw*/slc*/cms/PHEDEX-lifecycle/*/etc/profile.d/init.sh 
+. \$root/sw*/slc*/cms/asyncstageout/*/etc/profile.d/init.sh 
+
+# Remove old FakeFTS.pl from LifeCycle distribution! 
+(rm \$root/sw*/slc*/cms/PHEDEX-lifecycle/*/bin/FakeFTS.pl) 2>/dev/null 
+
+# Add PHEDEX-micro Utilities to the PATH 
+#export PATH=\${PATH}:\`ls -d \$root/sw*/slc*/cms/PHEDEX-micro/*/Utilities\`
+
+export PERL5LIB=\${PERL5LIB}:$ROOT_DIR/apps/asyncstageout/Monitor/perl_lib"  > $ROOT_DIR/apps/asyncstageout/Monitor/setup.sh
+
+    inited_asyncstageout;
+}
+
+#
+# initialise the async
+#
+init_asyncstageout(){
+
+    if [ $AS_INIT_DONE -eq 0 ]; then
+      echo "Initialising AsyncStageOut..."
+      init_async;
+    fi
+}
+
+start_asyncstageout(){
+    init_asyncstageout;
+    echo "Starting AsyncStageOut..."
+    wmcoreD --start --config=$CONFIG_AS/config.py
+    source $ROOT_DIR/apps/asyncstageout/Monitor/setup.sh
+    $ROOT_DIR/apps/asyncstageout/Monitor/ASO-Monitor.pl --config $CONFIG_AS/monitor.conf
+}
+
+stop_asyncstageout(){
+    echo "Shutting down asyncstageot...";
+    wmcoreD --shutdown --config=$CONFIG_AS/config.py;
+    echo "Stopping: Monitor"
+    kill -9 `cat $INSTALL_AS/Monitor/aso-monitor.pid`
+}
+
+status_of_asyncstageout(){
+    echo "Status of Asyncstageout:"
+    wmcoreD --status --config=$CONFIG_AS/config.py
+}
+
+execute_command_asyncstageout(){
+    shift;
+    local RUNTHIS=$1
+    local ASYNCSTAGEOUT_BIN_DIR=$ROOT_DIR/apps/asyncstageout/bin
+    if [ ! -e $ASYNCSTAGEOUT_BIN_DIR/$1 ]; then
+        echo "$RUNTHIS is not a binary in asyncstageout/bin"
+        exit 1
+    fi
+    shift;
+    load_secrets_file;
+    export WMAGENT_CONFIG=$CONFIG_AS/config.py
+    echo "Executing $RUNTHIS $@ ..."
+    $RUNTHIS $@;
+}
+
+
+#
+# revert async back to pre initialised state & wipe out
+# everything currently in existence.
+clean_asyncstageout(){
+    load_secrets_file;
+    stop_asyncstageout;
+    # Todo: clean couchapps?
+    echo "Cleaning asyncstageout..."
+    rm -rf $INSTALL_AS/*
+    rm -f $CONFIG_AS/config.py;
+    rm -f $INSTALL_AS/.init
+
+}
+
+
+status(){
+    load_secrets_file;
+    status_of_couch;
+    status_of_asyncstageout;
+}
+
+clean_all(){
+    clean_couch;
+    clean_asyncstageout;
+}
+
+help(){
+    echo "Documentation for this script can be found at: https://svnweb.cern.ch/trac/CMSDMWM/wiki/AsyncStageOutManagement";
+}
+#######################################################
+# Main
+#######################################################
+
+case $1 in
+  status)
+    status ;;
+  activate-asyncstageout)
+    activate_asyncstageout;;
+  start-services)
+     start_services;;
+  stop-services)
+     stop_services;;
+  start-couch)
+     start_couch;;
+  stop-couch)
+     stop_couch;;
+  clean-couch)
+     clean_couch;;
+  init-asyncstageout)
+     init_asyncstageout;;
+  start-asyncstageout)
+     start_asyncstageout;;
+  stop-asyncstageout)
+     stop_asyncstageout;;
+  clean-asyncstageout)
+     clean_asyncstageout;;
+  clean-all)
+     clean_all;;
+  execute-asyncstageout)
+     execute_command_asyncstageout $@;;
+  version)
+    echo "Management script for AsyncStageOut version 0" ;;
+  * )
+    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
+    exit 1 ;;
+esac
+
